DROP TABLE IF EXISTS switch;
DROP TABLE IF EXISTS ports;
DROP TABLE IF EXISTS specs;

CREATE TABLE switch (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  devicename TEXT UNIQUE NOT NULL,
  companyname TEXT NOT NULL,
  TEXT UNIQUE NOT NULL,
  modelnamenum TEXT NOT NULL,
  serialnum INTEGER NOT NULL
);

CREATE TABLE ports (
  megabyteRJ45 INTEGER NOT NULL,
  gigabitRJ45 INTEGER NOT NULL,
  sfp INTEGER NOT NULL,
  sfplus INTEGER NOT NULL,
  SFP28 INTEGER NOT NULL,
  QSFP+ INTEGER NOT NULL,
  QSFP28 INTEGER NOT NULL,
  POE INTEGER NOT NULL,
  FOREIGN KEY (port_id) REFERENCES switch (id)
);

CREATE TABLE specs (
  power INTEGER NOT NULL,
  minpower INTEGER NOT NULL,
  maxpower INTEGER NOT NULL,
  rackmounts BOOLEAN NOT NULL,
  weightkg INTEGER NOT NULL,
  lenghtcm INTEGER NOT NULL,
  widthcm INTEGER NOT NULL,
  heightcm INTEGER NOT NULL,
  managed BOOLEAN NOT NULL,
  FOREIGN KEY (spec_id) REFERENCES switch (id)
);