---
- name: "Ping the local system"
  ping:

- name: Write setup to file
  copy:                                                                                              
    content: "{{ ansible_facts }}" 
    dest: "{{project_home}}/ansible/setup_output.txt"
        
- name: "Apt update"
  become: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: "Upgrade all packages to their latest version"
  become: yes
  apt:
    upgrade: 'full'

- name: "Install Necessary Packages"
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'gnupg2'
    - 'curl'
    - 'gnupg'
    - 'lsb-release'
    - 'software-properties-common'
    - 'python3-pip'
    - 'virtualenv'
    - 'python3-setuptools'
    - 'intel-gpu-tools'
    - 'mergerfs'
    - 'snapraid'

- name: "Switch to pip3"
  alternatives:
    name: pip
    link: /usr/bin/pip
    path: /usr/bin/pip3

- name: "Switch to python3"
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3