---
- name: Package Installation and Setup Tasks
  tags: [packages, install]
  become: True
  block:
  - name: "Apt update"
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: "Upgrade all packages to their latest version"
    apt:
      upgrade: 'full'

  - name: "Install Necessary Packages"
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'gnupg2'
      - 'curl'
      - 'gnupg'
      - 'lsb-release'
      - 'software-properties-common'
      - 'python3-pip'
      - 'virtualenv'
      - 'python3-setuptools'
      - 'intel-gpu-tools'
      - 'mergerfs'
      - 'docker'

  - name: "Switch to pip3"
    alternatives:
      name: pip
      link: /usr/bin/pip
      path: /usr/bin/pip3

  - name: "Switch to python3"
    alternatives:
      name: python
      link: /usr/bin/python
      path: /usr/bin/python3
  
  rescue:
  - name: Print when errors occur
    ansible.builtin.debug:
      msg: 'There has been an error when attempting to setup the packages portion of the setup role, please edit and try again'