---
- name: "Curl Docker GPG Key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker repository to apt"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: "Install Docker and related packages"
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Enable Docker"
  service:
    name: docker
    state: started
    enabled: yes

- name: "Create Docker group"
  ansible.builtin.group:
    name: docker
    state: present

- name: "Add {{server_user_name}} to Docker group"
  user:
    name: "{{server_user_name}}"
    groups: docker
    append: yes

- name: "Display the groups that {{server_user_name}} is in"
  shell: "groups {{server_user_name}}"
  register: group_output

- debug: var=group_output['stdout']

- name: Install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /usr/local/bin/docker-compose
    owner: "{{server_user_name}}"
    group: "{{server_user_name}}"