---
- hosts: nasether
  name: "Initial checks"

  vars_files:
    - GroupVars/nas-vault.yml

  tasks:
    - name: "Ping the local system"
      ping:

    - name: "Install Software for Power Constraint"
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - 'lm-sensors'
        - 'pm-utils'
        - 'powertop'
        - 'fancontrol'
        - 'laptop-mode-tools'

    - name: "Disable Docker"
      service:
        name: docker
        state: stopped
        enabled: no

    - name: "Turn on pm-powersave"
      become: yes
      ansible.builtin.shell:
        cmd: pm-powersave true

    - name: "Setting Sata link power management to medium_power"
      become: yes
      ansible.builtin.shell:
        cmd: 
          - echo 'medium_power'> /sys/class/scsi_host/host0/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host1/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host2/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host3/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host4/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host5/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host6/link_power_management_policy
          - echo 'medium_power'> /sys/class/scsi_host/host7/link_power_management_policy
#sudo pwmconfig #checking fan sensors
# Bad           NMI watchdog should be turned off                                                                      
# Bad           VM writeback timeout
# Bad           Enable SATA link power management for host7
# Bad           Enable SATA link power management for host5
# Bad           Enable SATA link power management for host3
# Bad           Enable SATA link power management for host1
# Bad           Enable SATA link power management for host4
# Bad           Enable SATA link power management for host2
# Bad           Enable SATA link power management for host0
# Bad           Enable SATA link power management for host6
# Bad           Runtime PM for I2C Adapter i2c-1 (AST i2c bit bus)
# Bad           Autosuspend for USB device mini keyboard [ ]
# Bad           Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family Thermal Subsystem
# Bad           Runtime PM for port ata4 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for port ata1 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for PCI Device Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for disk sdf
# Bad           Runtime PM for port ata5 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for disk sdd
# Bad           Runtime PM for disk sde
# Bad           Runtime PM for disk sdc
# Bad           Runtime PM for PCI Device ASPEED Technology, Inc. ASPEED Graphics Family
# Bad           Runtime PM for disk sda
# Bad           Runtime PM for disk sdb
# Bad           Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #2
# Bad           Runtime PM for port ata3 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for port ata6 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for port ata2 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family MEI Controller #1
# Bad           Runtime PM for port ata8 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family Power Management Controller
# Bad           Runtime PM for PCI Device Intel Corporation C236 Chipset LPC/eSPI Controller
# Bad           Runtime PM for PCI Device ASPEED Technology, Inc. AST1150 PCI-to-PCI Bridge
# Bad           Runtime PM for PCI Device Samsung Electronics Co Ltd Device a809
# Bad           Runtime PM for port ata7 of PCI device: Intel Corporation Q170/Q150/B150/H170/H110/Z170/CM236 Chipset SATA Controller [AHCI Mode]
# Bad           Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family USB 3.0 xHCI Controller
# Good          Runtime PM for I2C Adapter i2c-0 (SMBus I801 adapter at f000)
# Good          Autosuspend for USB device xHCI Host Controller [usb1]
# Good          Autosuspend for USB device xHCI Host Controller [usb2]
# Good          Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #9
# Good          Runtime PM for PCI Device Intel Corporation Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
# Good          Runtime PM for PCI Device Intel Corporation Ethernet Connection (2) I219-LM
# Good          Runtime PM for PCI Device Intel Corporation I210 Gigabit Network Connection
# Good          Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #6
# Good          Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family SMBus
# Good          Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #8
# Good          Runtime PM for PCI Device Intel Corporation 100 Series/C230 Series Chipset Family PCI Express Root Port #1
