---
- hosts: nasether
  name: "Initial checks"

  vars_files:
    - GroupVars/nas-vault.yml
    - GroupVars/server-vars.yml

  tasks:
    - name: "Ping the local system"
      ping:

    - name: "Enable Docker"
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: "Create Docker group"
      ansible.builtin.group:
        name: docker
        state: present
    
    - name: "Add {{server_user_name}} to Docker group"
      user:
        name: "{{server_user_name}}"
        groups: docker
        append: yes

    - name: "Display the groups that {{server_user_name}} is in"
      become: yes
      shell: groups
      register: group_output

    - debug: var=group_output