---
- name: Install python3 and pip
  package:
    name:
      - python3
      - python3-pip
    state: latest

- name: Install github3 module
  pip:
    name: 
      - github3.py

- name: Check if blackbox_exporter is installed
  stat:
    path: /usr/local/bin/blackbox_exporter
  register: blackbox_exporter
  
- name: Check the blackbox_exporter version if installed
  shell:
    cmd: "blackbox_exporter --version 2>&1 | grep -o '[0-9]\\.[0-9]*\\.[0-9]*' -m 1"
  register: blackbox_exporter_version
  when: blackbox_exporter.stat.exists
  changed_when: False

- name: Set current blackbox_exporter version to 0 if not installed
  set_fact:
    blackbox_exporter_version:
      stdout: "0"
  when: not blackbox_exporter.stat.exists

- name: Check latest blackbox_exporter release
  github_release:
    user: prometheus
    repo: blackbox_exporter
    action: latest_release
    token: "{{ github_token }}"
  register: blackbox_exporter_release
  changed_when: blackbox_exporter_release.tag != ("v" + blackbox_exporter_version.stdout)

- name: Install latest blackbox_exporter
  when: blackbox_exporter_release.tag != ("v" + blackbox_exporter_version.stdout)
  block:
  - name: Create a temp directory
    file:
      path: /tmp/blackbox_exporter
      recurse: yes
      state: directory
      mode: 0755

  - name: Download the latest release
    unarchive: 
      remote_src: yes
      src: "https://github.com/prometheus/blackbox_exporter/releases/download/{{ blackbox_exporter_release.tag }}/blackbox_exporter-{{ blackbox_exporter_release.tag | regex_replace('^v','') }}.linux-{{ arch }}.tar.gz"
      dest: "/tmp/blackbox_exporter"

  - name: Copy the binary
    become: yes
    copy: 
      src: "/tmp/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter_release.tag | regex_replace('^v','') }}.linux-{{ arch }}/blackbox_exporter"
      remote_src: true
      dest: "/usr/local/bin/blackbox_exporter"
      mode: 0755
  
  - name: Create a config directory
    become: yes
    file:
      path: /etc/blackbox_exporter
      recurse: yes
      state: directory
      mode: 0755

  - name: Copy the config
    become: yes
    copy: 
      src: "/tmp/blackbox_exporter/blackbox_exporter-{{ blackbox_exporter_release.tag | regex_replace('^v','') }}.linux-{{ arch }}/blackbox.yml"
      remote_src: true
      dest: "/etc/blackbox_exporter/blackbox.yml"
      mode: 0644
 
  - name: Delete the temporary directory
    file:
      path: /tmp/blackbox_exporter
      state: absent

- name: Copy the systemd service file
  become: yes
  copy:
    src: files/blackbox_exporter.service
    dest: /etc/systemd/system/blackbox_exporter.service
    mode: 0755
  notify:
    - systemd reload

- name: Make sure that the systemd service is started
  become: yes
  systemd:
    service: blackbox_exporter
    enabled: yes
    state: started
