FROM ubuntu:22.04

# RUN apt-get update && apt-get install -y firefox

# # Replace 1000 with your user / group id
# RUN export uid=1000 gid=1000
# RUN mkdir -p /home/developer
# RUN echo "developer:x:${uid}:${gid}:Developer:/home/developer:/bin/bash" >> /etc/passwd
# RUN echo "developer:x:${uid}:" >> /etc/group
# RUN mkdir /etc/sudoers.d
# RUN touch /etc/sudoers.d/developer
# RUN echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer
# RUN chmod 0440 /etc/sudoers.d/developer
# RUN chown ${uid}:${gid} -R /home/developer

# USER developer
# ENV HOME /home/developer
# CMD /usr/bin/firefox

FROM centos:7
RUN yum install -y firefox
RUN yum install -y libcanberra-gtk2
RUN yum install -y PackageKit-gtk3-module
CMD ["/usr/bin/firefox"]