---
- hosts: arch-linux
  name: "Initial checks"

  vars_files:
    - GroupVars/Arch-Vars.yml

  roles:
    - DriveSetup
    - SoftwareInstall
    - SecuritySetup
    - BackupPull

    # https://github.com/badele/ansible-archlinux