---
- name: Docker Setup Tasks
  tags: docker
  become: True
  block:
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: install docker
    apt:
      name: "{{item}}"
      state: latest
      update_cache: yes
    loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: "Enable Docker Service"
    service:
      name: docker
      state: started
      enabled: yes
    
  - name: "Create Docker group"
    ansible.builtin.group:
      name: docker
      state: present

  - name: "Add {{test_server_user_name}} to Docker group"
    user:
      name: "{{test_server_user_name}}"
      groups: docker
      append: yes

  - name: "Display the groups that {{test_server_user_name}} is in"
    shell: groups
    register: group_output

  - debug: var=group_output

  - name: Install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Change file ownership, group and permissions
    ansible.builtin.file:
      path: /usr/local/bin/docker-compose
      owner: "{{test_server_user_name}}"
      group: "{{test_server_user_name}}"

  rescue:
  - name: Print when errors occur
    ansible.builtin.debug:
      msg: 'There has been an error when attempting to setup the docker portion of the setup role, please edit and try again'