name: Ansible Staging 01 - NAS
run-name: ${{ github.actor }} has pushed to the Ansible staging area used for NAS development
on: 
  push:
    branches:
      - 'ansible-staging-01'
jobs:
  Run-Testing-Script:
    runs-on: ubuntu-latest
    #runs-on: macos-10.15
    steps:

      - name: "Checkout Branch"
        uses: 'actions/checkout@v4'

      - name: "Display the Working Directory"
        run: echo "The working directory is - ${PWD}"

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: "Install Ansible Dependencies"
        run: pip install ansible-core

      - name: "Run Test Setup Script"
        run: "${PWD}/Github-Scripts/github-action.sh as01"


# Merge if all successful
# Copy changes to the productions branch if they are contained within the testing folder, if not leave alone
