name: Ansible Staging 01 - NAS
run-name: ${{ github.actor }} has pushed to the Ansible staging area used for NAS development
on: 
  push:
    branches:
      - 'ansible-staging-01'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Branch"
        uses: 'actions/checkout@v4'

      - name: "Install Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' 

      - name: "Install Ansible Dependencies"
        run: pip install ansible-core

      - name: "Display the Working Directory"
        run: echo "The working directory is - ${PWD}"
      
      - name: "Run Test Setup Script"
        run: "${PWD}/NAS-Server-Ansible-Docker/testing/scripts/setup.sh"

#wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
#echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
#sudo apt update && sudo apt install vagrant
# Merge if all successful
# Copy changes to the productions branch if they are contained within the testing folder, if not leave alone
